---
- name: Install IdM
  hosts: ipaserver
  become: true
  gather_facts: false
  tasks:
  - name: Create Host Records
    freeipa.ansible_freeipa.ipadnsrecord:
      ipaadmin_password: "{{ ipaadmin_password }}"
      zone_name: "{{ ipaserver_domain }}"
      records: "{{ dns_a_records }}"

